### ISSUE TITLE
IPF-11

### ISSUE THREAD

**Issue by Josh-Danks** [jopokemine/memory-palace#11]
The user will be able to create a rough floor plan of rooms.

- [x] User can click and drag/define room dimensions. - 2 Days
- [x] #27
- [x] Users can enter room information such as name. - 1 Day

- [x] Create local data storage - 2 Days

**Comment by JoshuaOC97** [comment]
Current Prototype and some documentation for it has been uploaded to the Drive. Please review in case concepts need changing.

**Comment by JoshuaOC97** [comment]
New version has been submitted to the Drive. Prototype will be completed and translated into C# soon.

**Comment by jopokemine** [comment]
After completing the setup steps in [IPF-15](https://github.com/jopokemine/memory-palace/issues/15), I suggest the following:

- When adding bluetooth devices, the user should be prompted to enter what room the device is in
- The user should then be presented with a (pseudo-?)random 3 character string which will be used to uniquely identify the device (to differentiate against other devices in the same room)
- In the backend, the name of the device should be `mem_pal_{room}_{identifier}`

This allows for much easier searching and setup for each bluetooth device.

**Comment by GenericGitHubProfile** [comment]
Found issue of UI element scaling:
Canvas scales to screen size which for the defined screen dimensions results in it being roughly 1 sixth scaling.
Needs to be resolved on an individual level for subelements, as otherwise canvas becomes un-usable.

**Comment by Josh-Danks** [comment]
> 

Resolved

**Comment by Josh-Danks** [comment]
> Found issue of UI element scaling: Canvas scales to screen size which for the defined screen dimensions results in it being roughly 1 sixth scaling. Needs to be resolved on an individual level for subelements, as otherwise canvas becomes un-usable.

Resolved

**Comment by Josh-Danks** [comment]
-Task added to create local storage

**Comment by GenericGitHubProfile** [comment]
Fixed issue with resize button positioning being incorrect.
When manipulating GameObject transforms, use "local" prefixes, i.e. localScale, localPosition, etc. to make them relative to the parent element.

**Comment by Josh-Danks** [comment]
-Task has been broken down into Issue-27
-Danks to do data storage

**Comment by GenericGitHubProfile** [comment]
Development of Watson API integration took priority, as such this was not finished
