### ISSUE TITLE
IPF-15

### ISSUE THREAD

**Issue by Josh-Danks** [jopokemine/memory-palace#15]
The application will be able to determine what room the user is currently in

_**Dependancy IPF-11**_
_**Dependancy IPF-22**_

- [x] Raspberry PI set up script
- [x] User device gets Bluetooth strength and room data from raspberry PI's
- [x] Get Unity to probe Pi's for signal strength - 1/2 Day
- [x] Check strongest bluetooth signal - 1/2 Day
- [x] Triangulates position (IPF-22)
- [x] Translates it to grid coordinates - 3 Days
- [x] Test ability to find user in room - 1/2 Day

**Comment by JoshuaOC97** [comment]
Current notes and prototype will be uploaded to the Drive tonight; they just need to be cleaned up a bit to be easily understood.

**Comment by JoshuaOC97** [comment]
Current prototype now uploaded to Drive and some documentation to go with it. Please review to ensure everything can connect.

**Comment by jopokemine** [comment]
Just had a look at the documentation, it looks good. However I think the assumption that we don't know the location of the bluetooth devices is wrong. I'm pretty sure part of the initial setup steps is for the user to tell the app where their bluetooth devices are in the room, so we can use that position to help locate the user.

**Comment by JoshuaOC97** [comment]
Understood, I'll make some changes. I think most of the stuff will be the same but the first few steps will be different.

**Comment by JoshuaOC97** [comment]
New version has been submitted to the Drive. Prototype will be completed and translated into C# soon.

**Comment by jopokemine** [comment]
The setup script has been completed, and the server to relay the Bluetooth RSSI is functionally complete (the only changes are to reformat the returned information if needed). The setup script will change the hostname of the device to `mem_pal_{room}_{identifier}`, where the room and identifier (defined in [IPF-11](https://github.com/jopokemine/memory-palace/issues/11)) are passed as parameters when running the script. Doing this means it will be easier to identify the devices when searching for the user's location

**Comment by Josh-Danks** [comment]
-Check coordinates against rooms changed to Check strongest bluetooth signal
-Added Get Unity to probe Pi's for signal strength
-Added IPF-22 dependency

**Comment by Josh-Danks** [comment]
-Waiting on Hugh for GET request (complete but not merged)
-Task reduced to 1 days work

**Comment by Josh-Danks** [comment]
-GET requests work however Flask server wasn't working
-Code for tasks is there just needs testing
-Danks to send JSON code

**Comment by jopokemine** [comment]
Moved code for all my issues (#15 #18 #20 #21 #24) into one branch (jopokemine) to make things a bit easier

**Comment by jopokemine** [comment]
Added test task so implementation tasks can be marked as done

**Comment by jopokemine** [comment]
Finished in latest commits
