### ISSUE TITLE
IPF-20

### ISSUE THREAD

**Issue by Josh-Danks** [jopokemine/memory-palace#20]
The application will path the user to the item location using AR

**_Dependency IPF-11_**
**_Dependency IPF-18_**
**_Dependency IPF-19_**
**_Dependency IPF-2/17_**

- [x] Get users current position 
- [x] Get item position
- [x] Calculate route in the current room (will ask the user to go to the correct room if they are not their already)
- [x] Test the route and thus arrow position (#21) are correct

**Comment by jopokemine** [comment]
#21 is essentially a duplicate of the task "PRoject arrow in AR", so I will remove this task. As such, I will also unassign #Josh-Danks, since they are already assigned to #21

**Comment by jopokemine** [comment]
Finished in latest commits
